### ISSUE TITLE
fabric.js适用于移动端吗？

### ISSUE THREAD

**Issue by awesomezz** [Luckly-together/Fabric-Tutorial_zh-CN#2]
你好， mouse:weel缩放 平移有适用于移动端 手指捏放的方法吗？没找到对应的方法

**Comment by liuxsen** [comment]
> 你好， mouse:weel缩放 平移有适用于移动端 手指捏放的方法吗？没找到对应的方法

你解决了吗

**Comment by awesomezz** [comment]
> > 你好， mouse:weel缩放 平移有适用于移动端 手指捏放的方法吗？没找到对应的方法
> 
> 你解决了吗

没有，放在父级元素div身上了。单独的写的。缩放
