### ISSUE TITLE
记录一下已经过时的内容

### ISSUE THREAD

**Issue by zhangyunihao** [Luckly-together/Fabric-Tutorial_zh-CN#5]
var gradient = new fabric.Gradient({
  type: 'linear',
  gradientUnits: 'pixels', // or 'percentage'
  coords: { x1: 0, y1: 0, x2: 0, y2: circle.height },
  colorStops:[
    { offset: 0, color: '#000' },
    { offset: 1, color: '#fff'}
  ]
})

circle.set('fill', gradient);

**Comment by zhangyunihao** [comment]
group.item(0).set('fill', 'red');
group.item(1).set({
  text: 'trololo',
  fill: 'white'
});

**Comment by zhangyunihao** [comment]
这个原版也不对，应该是
canvas.toDataURL({format: 'png'})

**Comment by zhangyunihao** [comment]
所有代码的括号应该是英文的

**Comment by zhangyunihao** [comment]
canvas.loadFromJSON('{"objects":[{"type":"rect","left":50,"top":50,"width":20,"height":20,"fill":"green","overlayFill":null,"stroke":null,"strokeWidth":1,"strokeDashArray":null,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":1,"selectable":true,"hasControls":true,"hasBorders":true,"hasRotatingPoint":false,"transparentCorners":true,"perPixelTargetFind":false,"rx":0,"ry":0},{"type":"circle","left":100,"top":100,"width":100,"height":100,"fill":"red","overlayFill":null,"stroke":null,"strokeWidth":1,"strokeDashArray":null,"scaleX":1,"scaleY":1,"angle":0,"flipX":false,"flipY":false,"opacity":1,"selectable":true,"hasControls":true,"hasBorders":true,"hasRotatingPoint":false,"transparentCorners":true,"perPixelTargetFind":false,"radius":50}],"background":"rgba(0, 0, 0, 0)"}',
      () => { });
现在参数加了个callback

**Comment by hou-pu** [comment]
欢迎pr

**Comment by zhangyunihao** [comment]
与黑色像素重叠的对象的像素将是可见的，而与黑色像素重叠的对象的像素将是可见的。
这段话是笔误吧
The pixels of the object that overlap with the black pixels of the clipPath will be visible, while the other will not.
